name: Test
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 18, 20 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node }}
    steps:
      - name: Install prerequisites
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libunwind-dev 
          sudo apt-get install -y libgoogle-glog-dev
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info
      - name: Test Electron
        if: ${{ matrix.node == '14' }}
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test-electron
      - name: Test GC
        run: npm run test-gc
